# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='an', max_length=30, verbose_name='作者'),
        ),
    ]
