# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170522_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, verbose_name='联系者名字')),
                ('user_email', models.EmailField(max_length=200, verbose_name='联系者邮箱')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('body', models.TextField(verbose_name='内容')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-last_modified_time', '-created_time']},
        ),
    ]
