# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-03 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170523_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, verbose_name='标签名'),
        ),
    ]
